server:
  port: 8090

spring:
  cloud:
      gateway:
        routes:
          - id: user-service
            name: user-service
            uri: http://localhost:8092/
            predicates:
              - Path=/user/**
          - id: product-service
            name: product-service
            uri: http://localhost:8091/
            predicates:
              - Path=/product/**

  application:
    name: api-gateway